-- -----------------------------------------------------
-- Schema CHECKPOINT3 - BANCO DE DADOS LOJA DE ROUPAS
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS CHECKPOINT3 DEFAULT CHARACTER SET utf8 ;
USE CHECKPOINT3 ;

CREATE TABLE IF NOT EXISTS CHECKPOINT3.FUNCIONARIO (
  ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL,
  SOBRENOME VARCHAR(45) NOT NULL,
  ATIVO TINYINT NOT NULL,
  USUARIO VARCHAR(45),
  SENHA VARCHAR(45),
  ATULAIZACAO TIMESTAMP NOT NULL,
  LOGRADOURO VARCHAR(45),
  CIDADE VARCHAR(45),
  ESTADO VARCHAR(2),
  CEP VARCHAR(45),
  COMPLEMENTO VARCHAR(45),
  CONTATO VARCHAR(45),
  EMAIL VARCHAR(45),
  PRIMARY KEY (ID_FUNCIONARIO))

CREATE TABLE IF NOT EXISTS CHECKPOINT3.FORNECEDOR (
  ID_FORNECEDOR INT NOT NULL AUTO_INCREMENT,
  NOME FANTASIA VARCHAR(45) NOT NULL,
  CNPJ_CPF VARCHAR(45) NOT NULL,
  LOGRADOURO VARCHAR(45),
  CIDADE VARCHAR(45),
  ESTADO VARCHAR(2),
  CEP VARCHAR(45),
  COMPLEMENTO VARCHAR(45),
  CONTATO VARCHAR(45),
  EMAIL VARCHAR(45),
  PRIMARY KEY (ID_FORNECEDOR))

CREATE TABLE IF NOT EXISTS CHECKPOINT3.ENTRADA_PRODUTO (
  ID_ENTRADA_PRODUTO INT NOT NULL AUTO_INCREMENT,
  ID_FORNECEDOR INT NOT NULL,
  DESCRICAO VARCHAR(45) NOT NULL,
  QUANTIDADE INT NOT NULL,
  VALOR_COMPRA DECIMAL NOT NULL,
  PRIMARY KEY (ID_ENTRADA_PRODUTO),
  CONSTRAINT ID_COMPRA_ID_FORNECEDOR_ID_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR)  REFERENCES CHECKPOINT3.FORNECEDOR (ID_FORNECEDOR) )

CREATE TABLE IF NOT EXISTS CHECKPOINT3.ESTOQUE (
  ID_ESTOQUE INT NOT NULL AUTO_INCREMENT,
  ID_ENTRADA_PRODUTO INT NOT NULL,
  DESCRICAO VARCHAR(45) NOT NULL,
  QUANTIDADE VARCHAR(45) NOT NULL,
  VALOR_VENDA DECIMAL NOT NULL,
  PRIMARY KEY (ID_ESTOQUE),  
  CONSTRAINT ESTOQUE_ID_COMPRA FOREIGN KEY (ID_ENTRADA_PRODUTO) REFERENCES CHECKPOINT3.ENTRADA_PRODUTO (ID_ENTRADA_PRODUTO))

CREATE TABLE IF NOT EXISTS CHECKPOINT3.CLIENTE (
  ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(45) NOT NULL,
  SOBRENOME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50),
  TELEFONE VARCHAR(50),
  ATIVO TINYINT NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  ATUALIZACAO TIMESTAMP NOT NULL,
  LOGRADOURO VARCHAR(45),
  CIDADE VARCHAR(45),
  ESTADO VARCHAR(2),
  CEP VARCHAR(45),
  COMPLEMENTO VARCHAR(45),
  PRIMARY KEY (ID_CLIENTE))

CREATE TABLE IF NOT EXISTS CHECKPOINT3.SAIDA_PRODUTO (
  ID_SAIDA_PRODUTO INT NOT NULL AUTO_INCREMENT,
  ID_CLIENTE INT NOT NULL,
  ID_FUNCIONARIO INT NOT NULL,
  ID_ESTOQUE INT NOT NULL,
  PRIMARY KEY (ID_SAIDA_PRODUTO),
  CONSTRAINT VENDAS_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES CHECKPOINT3.FUNCIONARIO (ID_FUNCIONARIO),
  CONSTRAINT VENDAS_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CHECKPOINT3.CLIENTE (ID_CLIENTE),  
  CONSTRAINT VENDAS_ID_ESTOQUE FOREIGN KEY (ID_ESTOQUE) REFERENCES CHECKPOINT3.ESTOQUE (ID_ESTOQUE))
