USE CHECKPOINT3;

-- -----------------------------------------------------
-- TABELA FUNCIONARIO
-- -----------------------------------------------------

INSERT INTO  FUNCIONARIO (NOME, SOBRENOME, ATIVO, USUARIO, SENHA, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CONTATO, EMAIL) 
VALUES ('PAULO','BORGES', FALSE, 'paulo.borges', 'Mudar1234', '2022-01-20 19:00:00', 'RUA DA JABOTICABA', 'LAGES', 'SC', '88523480', 'SEM COMPLEMENTO', '1999587639','PAULO.BORGES@DIGITALHOUSE.COM');

INSERT INTO  FUNCIONARIO (NOME, SOBRENOME, ATIVO, USUARIO, SENHA, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CONTATO, EMAIL) 
VALUES ('LAURA','FREITAS', TRUE, 'laura.freitas', 'Mudar1234', '2022-03-27 20:10:00', 'RUA DA FLORES', 'SÃO PAULO', 'SP', '06513480', 'PERTO DO BOSQUE', '1999658739','LAURA.FREITAS@DIGITALHOUSE.COM');

INSERT INTO  FUNCIONARIO (NOME, SOBRENOME, ATIVO, USUARIO, SENHA, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CONTATO, EMAIL) 
VALUES ('FELIPE','OTANI', TRUE, 'felipe.otani', 'Mudar1234', '2022-04-26 18:00:00', 'RUA DA FERROVIA', 'RIO DE JANEIRO', 'RJ', '05523120', 'NA RUA DA ESTRELA', '4199412549','FELIPE.OTANI@DIGITALHOUSE.COM');

INSERT INTO  FUNCIONARIO (NOME, SOBRENOME, ATIVO, USUARIO, SENHA, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CONTATO, EMAIL) 
VALUES ('IVANALDO','SANTOS', TRUE, 'ivanaldo.santos', 'Mudar1234', '2022-05-20 10:00:00', 'RUA DA ESTRADAS', 'CURITIBA', 'PR', '09523410', 'COMPLENTO DAS RUAS', '4599432539','IVANALDO.SANTOS@DIGITALHOUSE.COM');

SELECT * FROM FUNCIONARIO;

-- -----------------------------------------------------
-- TABELA FORNECEDOR
-- -----------------------------------------------------

INSERT INTO  FORNECEDOR (NOME_FANTASIA,CNPJ_CPF, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CONTATO, EMAIL) 
VALUES ('CENTRO DAS MALAHS','23886835000196', 'RUA DA MALHAS','CURITIBA', 'PR', '09542089', 'COMPLEMENTO DAS MALHAS', '32518000', 'CENTRODASMALHAS@DIGITALHOUSE.COM');

INSERT INTO  FORNECEDOR (NOME_FANTASIA,CNPJ_CPF, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CONTATO, EMAIL) 
VALUES ('MALHAS FACIL','64590492000103', 'RUA DA FLORES','LAGES', 'SC', '32542089', 'COMPLEMENTO DA CIDADE', '32548000', 'MALHASFACIL@DIGITALHOUSE.COM');

INSERT INTO  FORNECEDOR (NOME_FANTASIA,CNPJ_CPF, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CONTATO, EMAIL) 
VALUES ('DISTRIBUIDORA DE MALHAS','62932684000117', 'RUA DA MARGARIDA','SANTO ANGELO', 'RS', '06252089', 'COMPLEMENTO PERTO DA LOTERICA', '39876000', 'CENTRODASMALHAS@DIGITALHOUSE.COM');

SELECT * FROM FORNECEDOR;


-- -----------------------------------------------------
-- TABELA ENTRADA_PRODUTO
-- -----------------------------------------------------

INSERT INTO ENTRADA_PRODUTO (ID_FORNECEDOR,DESCRICAO, QUANTIDADE, VALOR_COMPRA, TAMANHO) 
VALUES (1,'CALÇA PRETA JEAN', 20, 39.99, 'P');

INSERT INTO ENTRADA_PRODUTO (ID_FORNECEDOR,DESCRICAO, QUANTIDADE, VALOR_COMPRA, TAMANHO) 
VALUES (2,'CALÇA BRANCA JEAN', 18, 41.99, 'PP');

INSERT INTO ENTRADA_PRODUTO (ID_FORNECEDOR,DESCRICAO, QUANTIDADE, VALOR_COMPRA, TAMANHO) 
VALUES (3,'CALÇA ROSA JEAN', 16, 49.99, 'GG');

INSERT INTO ENTRADA_PRODUTO (ID_FORNECEDOR,DESCRICAO, QUANTIDADE, VALOR_COMPRA, TAMANHO) 
VALUES (1,'JAQUETA AZUL MARINHO JEAN', 15, 29.99, 'G');

INSERT INTO ENTRADA_PRODUTO (ID_FORNECEDOR,DESCRICAO, QUANTIDADE, VALOR_COMPRA, TAMANHO) 
VALUES (2,'JAQUETA PRETA JEAN', 10, 19.99, 'M');

INSERT INTO ENTRADA_PRODUTO (ID_FORNECEDOR, DESCRICAO, QUANTIDADE, VALOR_COMPRA, TAMANHO) 
VALUES (3,'JAQUETA PRETA JEAN', 5, 59.99, 'P');

SELECT * FROM ENTRADA_PRODUTO;


-- -----------------------------------------------------
-- TABELA DE CLIENTE
-- -----------------------------------------------------

INSERT INTO CLIENTE (NOME, SOBRENOME, EMAIL, TELEFONE, ATIVO, DATA_CRIACAO, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CPF_CNPJ) 
 VALUES ('Henry','Pereira','henry@henry.com.br', '9129694324', TRUE, '2022-05-20 10:00:00', '2022-05-22 19:00:00', 'Passagem Nazaré', 'Ananindeua', 'PA', '67120560', 'box52', '69959656047' );
 
INSERT INTO CLIENTE (NOME, SOBRENOME, EMAIL, TELEFONE, ATIVO, DATA_CRIACAO, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CPF_CNPJ) 
VALUES ('Heloise Andrea Caroline','Freitas','heloiseandreafreitas@allurepesquisa.com.br', '8439776125',true , '2022-03-18 10:00:00', '2022-04-22 21:00:00', 'Avenida Wilson Rosado', 'Nova Betânia', 'RN', '67120560', 'Rua da laranjeira', '00422059056');

INSERT INTO CLIENTE (NOME, SOBRENOME, EMAIL, TELEFONE, ATIVO, DATA_CRIACAO, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CPF_CNPJ) 
VALUES ('Márcia Mariah Eliane','Pereira','marcia-silveira75@marcofaria.com', '9229703191',true , '2021-03-10 15:00:00', '2022-06-22 11:00:00', 'Passagem Virgem de Nazaré', 'Ananindeua', 'PA', '67120560', 'sem complemento', '73570818004');

INSERT INTO CLIENTE (NOME, SOBRENOME, EMAIL, TELEFONE, ATIVO, DATA_CRIACAO, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CPF_CNPJ) 
VALUES ('Mariah Sueli','Bruna Monteiro','mariah_sueli_monteiro@atualmarcenaria.com.br', '11984970742',true , '2022-05-20 10:00:00', '2022-05-22 19:00:00', 'Rua Francisco Ribeiro Júnior', 'Jardim América', 'SP', '12902340', 'próx a floricultura', '23197469003');

INSERT INTO CLIENTE (NOME, SOBRENOME, EMAIL, TELEFONE, ATIVO, DATA_CRIACAO, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CPF_CNPJ) 
VALUES ('Analu Esther','Fernanda da Cruz','analuestherdacruz@metododerose.org', '8637529582',true , '2022-05-20 10:00:00', '2022-05-22 19:00:00', 'Monte Castelo', 'Teresina', 'PI', '64016833', 'perto do parque nacional','37256959036');

INSERT INTO CLIENTE (NOME, SOBRENOME, EMAIL, TELEFONE, ATIVO, DATA_CRIACAO, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CPF_CNPJ) 
VALUES ('Maitê Carolina','Figueiredo','maite.carolina.figueiredo@valparaibaimoveis.com.br', '6928323904',false , '2022-05-20 10:00:00', '2022-05-22 19:00:00', 'Três Marias', 'Porto Velho', 'RO', '76812510', 'no bosque 23', '82291963031');

INSERT INTO CLIENTE (NOME, SOBRENOME, EMAIL, TELEFONE, ATIVO, DATA_CRIACAO, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CPF_CNPJ) 
VALUES ('Marcos Vinicius','Anthony Viana','marcos-viana87@haldex.com', '49998063560',true , '2022-05-20 10:00:00', '2022-05-22 19:00:00', 'Servidão Manoel dos Santos', 'Navegantes', 'SC', '88371009', 'rua sem saída', '08939272013');

INSERT INTO CLIENTE (NOME, SOBRENOME, EMAIL, TELEFONE, ATIVO, DATA_CRIACAO, ATUALIZACAO, LOGRADOURO, CIDADE, ESTADO, CEP, COMPLEMENTO, CPF_CNPJ) 
VALUES ('Rosângela Clara','Mendes','rosangela_mendes@robertacorrea.com', '6336566578',false , '2022-05-20 10:00:00', '2022-05-22 19:00:00', 'Residencial Jardim Europa', 'Araguaína', 'TO', '67120560', 'sem complemento indicado', '07475518043');

SELECT * FROM CLIENTE;


-- -----------------------------------------------------
-- TABELA FORMA PAGAMENTO
-- -----------------------------------------------------

INSERT INTO FORMA_PAGAMENTO (PAGAMENTO) 
VALUES ('À VISTA');

INSERT INTO FORMA_PAGAMENTO (PAGAMENTO) 
VALUES ('CARTÃO DEBITO');

INSERT INTO FORMA_PAGAMENTO (PAGAMENTO) 
VALUES ('CARTÃO CREDITO');

INSERT INTO FORMA_PAGAMENTO (PAGAMENTO) 
VALUES ('CHEQUE');

INSERT INTO FORMA_PAGAMENTO (PAGAMENTO) 
VALUES ('PERMUTA');

SELECT * FROM FORMA_PAGAMENTO;

-- -----------------------------------------------------
-- TABELA ESTOQUE
-- -----------------------------------------------------

INSERT INTO ESTOQUE (ID_ENTRADA_PRODUTO, DESCRICAO, QUANTIDADE, VALOR_VENDA) 
VALUES (1, 'CALÇA PRETA JEAN', 1, 80.00 );


INSERT INTO ESTOQUE (ID_ENTRADA_PRODUTO, DESCRICAO, QUANTIDADE, VALOR_VENDA) 
VALUES (3,'CALÇA ROSA JEAN', 2, 100.00);

-- -----------------------------------------------------
-- TABELA SAIDA PRODUTO
-- -----------------------------------------------------

INSERT INTO SAIDA_PRODUTO (ID_CLIENTE, ID_FUNCIONARIO, ID_ESTOQUE, ID_FORMA_PAGAMENTO) VALUES (1, 1, 1, 1);

SELECT * FROM SAIDA_PRODUTO;

-- -----------------------------------------------------
-- CRIAÇÃO DA VIEW
-- -----------------------------------------------------

CREATE VIEW vw_HistoricoCompras AS
SELECT 
    CLIENTE.CPF_CNPJ AS 'DOCUMENTO DO CLIENTE',
    CLIENTE.ID_CLIENTE AS 'ID DO CLIENTE',
    CLIENTE.NOME AS 'NOME',
    CLIENTE.SOBRENOME AS 'SOBRENOME', 
    ESTOQUE.ID_ESTOQUE AS 'ID DE VENDA',
    ESTOQUE.DESCRICAO AS 'PRODUTO',
    ESTOQUE.QUANTIDADE AS 'QUANTIDADE',
    ESTOQUE.VALOR_VENDA AS 'VALOR DA VENDA',
    (ESTOQUE.QUANTIDADE * ESTOQUE.VALOR_VENDA) AS 'VALOR TOTAL',
    FUNCIONARIO.ID_FUNCIONARIO AS 'ID VENDEDOR',
    FUNCIONARIO.NOME AS 'VENDEDOR'    
FROM 
	SAIDA_PRODUTO
INNER JOIN 
	CLIENTE ON CLIENTE.ID_CLIENTE = SAIDA_PRODUTO.ID_CLIENTE
INNER JOIN 
	FUNCIONARIO ON FUNCIONARIO.ID_FUNCIONARIO = SAIDA_PRODUTO.ID_FUNCIONARIO
INNER JOIN 
	ESTOQUE ON ESTOQUE.ID_ESTOQUE = SAIDA_PRODUTO.ID_ESTOQUE;
	

-- -----------------------------------------------------
-- VISUALIZAÇÃO DA VIEW
-- -----------------------------------------------------
    
SELECT * FROM vw_HistoricoCompras;



-- -----------------------------------------------------
-- ALTERAÇÃO DA CLIENTE
-- -----------------------------------------------------

-- ALTER TABLE CLIENTE ADD CPF_CNPJ VARCHAR(45);

-- -----------------------------------------------------
-- ALTERAÇÃO DA ENTRADA DE PRODUTO
-- -----------------------------------------------------

-- ALTER TABLE ENTRADA_PRODUTO ADD TAMANHO VARCHAR(2);
